service: hello

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  environment:
    MONGO_DB: ${env:MONGO_DB}


functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi: 
          method: GET
          path: /hello
          cors: true
  getAllPets:
    handler: src/handlers/pets.getAll
    events:
      - httpApi:
          method: GET
          path: /pets
          cors: true
  getPetById:
    handler: src/handlers/pets.getOne
    events:
      - httpApi:
          method: GET
          path: /pets/{id}
          cors: true
  createPet:
    handler: src/handlers/pets.create
    events:
      - httpApi:
          method: POST
          path: /pets
          cors: true

plugins:
  - serverless-esbuild
  - serverless-offline
